global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "BasicApi1"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:8001"]
        labels:
          group: "basicApi1_Group"
  - job_name: "BasicApi2"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:8002"]
        labels:
          group: "basicApi2_Group"
  